export const gods = {
  home: {
    name: 'The Architect',
    domain: '',
    symbol: '✦',
    lore: 'Before all things, the Architect shaped the void into form.',
    primary: '#D4AF37',
    secondary: '#8B6914',
    bg: 'radial-gradient(ellipse at 50% 0%, #1a1200 0%, #0a0800 50%, #000 100%)',
    gradient: 'linear-gradient(135deg, #D4AF37, #8B6914)',
    particle: { color: '#D4AF37', shape: 'star', count: 60 },
    path: '/',
  },
  about: {
    name: 'The Chronicler',
    domain: 'God of Knowledge & Wisdom',
    symbol: '◈',
    lore: 'All that was written, all that will be — the Chronicler has read it.',
    primary: '#9B59B6',
    secondary: '#4A235A',
    bg: 'radial-gradient(ellipse at 50% 0%, #1a0a2e 0%, #0d0618 50%, #000 100%)',
    gradient: 'linear-gradient(135deg, #9B59B6, #4A235A)',
    particle: { color: '#9B59B6', shape: 'circle', count: 50 },
    path: '/about',
  },
  projects: {
    name: 'The Forgemaster',
    domain: 'God of Craft & Fire',
    symbol: '⚒',
    lore: 'Every great work bears the Forgemaster\'s mark — shaped by heat and will.',
    primary: '#E74C3C',
    secondary: '#922B21',
    bg: 'radial-gradient(ellipse at 50% 100%, #2d0800 0%, #1a0400 50%, #000 100%)',
    gradient: 'linear-gradient(135deg, #E74C3C, #F39C12)',
    particle: { color: '#E74C3C', shape: 'ember', count: 70 },
    path: '/projects',
  },
  skills: {
    name: 'The Stormcaller',
    domain: 'God of Lightning & Swiftness',
    symbol: '⚡',
    lore: 'The storm does not ask permission. Neither does mastery.',
    primary: '#3498DB',
    secondary: '#1A5276',
    bg: 'radial-gradient(ellipse at 50% 0%, #001a2e 0%, #000d1a 50%, #000 100%)',
    gradient: 'linear-gradient(135deg, #3498DB, #85C1E9)',
    particle: { color: '#3498DB', shape: 'lightning', count: 45 },
    path: '/skills',
  },
  contact: {
    name: 'The Wayfinder',
    domain: 'God of Paths & Connection',
    symbol: '◎',
    lore: 'Every path leads somewhere. The Wayfinder knows where they all end.',
    primary: '#27AE60',
    secondary: '#1A5C38',
    bg: 'radial-gradient(ellipse at 50% 50%, #001a0d 0%, #000d06 50%, #000 100%)',
    gradient: 'linear-gradient(135deg, #27AE60, #A9DFBF)',
    particle: { color: '#27AE60', shape: 'wisp', count: 40 },
    path: '/contact',
  },
};

export const godList = Object.values(gods);
